
class LoginConstants:
    url = "https://qa.trado.co.il/api/user/login"
    valid_phone_valid_valid_code = '{"code":"12870","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_phone_invalid_code = {"code":"12870","phone":"4291111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    null_phone_null_code = {"code":"","phone":"","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_phone_invalid_code = {"code":"33333","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    invalid_phone_valid_code = {"code":"12870","phone":"4291111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_phone_null_code = {"code":"","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    null_phone_valid_code = {"code":"12870","phone":"","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    invalid_phone_null_code = {"code":"","phone":"4291111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    null_phone_invalid_code = {"code":"3333","phone":"","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    longValue_phone_valid_code = {"code":"12870","phone":"0591111113333","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    short_value_phone_valid_code = {"code":"12870","phone":"05911","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    longValue_phone_invalid_code = {"code":"33333","phone":"05911111133333","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    short_value_phone_invalid_code = {"code":"33333","phone":"05911","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    long_value_phone_null_code = {"code":"","phone":"05911111133333","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    short_value_phone_null_code = {"code":"","phone":"05911","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_phone_long_value_code = {"code":"12870000","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_value_phone_ShortValue_code = {"code":"12","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    stringValue_phone_valid_code = {"code":"12870","phone":"qwertfghujk","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_phone_stringValue_code = {"code":"zxcvv","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    SpecialCharacterValue_phone_valid_code = {"code":"12870","phone":"@#$%^&*()","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
    valid_phone_SpecialCharacter_code = {"code":"###$$","phone":"0591111113","type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}
