


class SearchConstrants:
    url = "https://qa.trado.co.il/api/product/filter"
    valid_existing_data = '{"search":"milk","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_non_exsting_product = '{"search":"wdtgsfdeuhvcwe c","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_null_data = '{"search":"","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_number_value = '{"search":"123456","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_special_character = '{"search":"@!#$%^","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_space_data = '{"search":" ","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_number_and_special = '{"search":"12345@#$%","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_number_and_string = '{"search":"milk56784","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_special_and_string = '{"search":"milk#@%^&*","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_only_one_character = '{"search":"m","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_multiple_string_product = '{"search":"goat milk","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'