
class SignupConstants:
    url ="https://qa.trado.co.il/api/user/registerUser"
    valid_phone = '{"phone":"1567353667","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_phone_less_than_10_digit = '{"phone":"1567353","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_phone_more_than_10_digit = '{"phone":"156735366745895","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_phone_null_digit = '{"phone":"","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_stringValue_phone  ='{"phone":"ghaghdfhagdh","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_specialCharacterValue_phone  ='{"phone":"@@@@######$$$%%","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_string_and_specialValue_phone  ='{"phone":"@@###$$fghhh","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_string_and_integer_phone  ='{"phone":"1567353667cjdsgs","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
    invalid_special_and_integerValue_phone  ='{"phone":"###$%%%1567353667","marketingList":true,"bnNumber":"1567353667","register":true,"type":"phone","info":{"lng":"hebrew","platform":"web","screenHeight":1080,"screenWidth":1920,"location":{"ancestorOrigins":{},"href":"https://qa.trado.co.il/","origin":"https://qa.trado.co.il","protocol":"https:","host":"qa.trado.co.il","hostname":"qa.trado.co.il","port":"","pathname":"/","search":"","hash":""}}}'
