import pytest
# from Web.Page import Login
from Web.Page.signup_page import SignUp
import time
import allure



class Test_Signup:

    @allure.description('Test_login_with_valid_credentials')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.sanity
    def test_signup_with_twitter_valid_credentials(self):
        signup = SignUp(self)
        signup.open_trado()
        signup .click_option1()
        signup.click_option2()
        signup.click_save_button()
        time.sleep(2)
        signup.click_on_connect_link()
        time.sleep(2)
        signup.click_on_signup_link()
        time.sleep(2)
        signup .click_on_twitter_link()
        time.sleep(8)
        signup .window_handle()
        time.sleep(8)
        signup.setUsername('getlove@test')
        signup .setPassword('test@@@###123')
        signup.click_on_signup_button()

    def test_signup_with_twitter_invalid_password_and_valid_username(self):
        signup  = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup .click_option2()
        signup .click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.click_on_twitter_link()
        time.sleep(8)
        signup .window_handle()
        time.sleep(8)
        signup .setUsername('getlove@test')
        signup.setPassword('testdsiu323')
        signup .click_on_signup_button()

    def test_signup_with_twitter_invalid_password_and_invalid_username(self):
        signup = SignUp(self)
        signup .open_trado()
        signup .click_option1()
        signup .click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.click_on_twitter_link()
        time.sleep(8)
        signup.window_handle()
        signup .setUsername('gedhcsdsyh')
        signup.setPassword('testdsiu323')
        signup.click_on_signup_button()

    def test_signup_with_twitter_valid_password_and_invalid_username(self):
        signup  = SignUp(self)
        signup.open_trado()
        signup .click_option1()
        signup.click_option2()
        signup .click_save_button()
        signup .click_on_connect_link()
        signup.click_on_signup_link()
        signup.click_on_twitter_link()
        signup .window_handle()
        time.sleep(8)
        signup .setUsername('gedhcsdsyh')
        signup .setPassword('test@@@###123')
        signup .click_on_signup_button()


    def test_signup_with_twitter_null_password_and_null_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup .click_on_twitter_link()
        signup .window_handle()
        time.sleep(8)
        signup.setUsername('')
        signup .setPassword('')
        signup.click_on_signup_button()


    def test_signup_with_twitter_null_password_and_valid_username(self):
        signup = SignUp(self)
        signup .open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup .click_on_twitter_link()
        time.sleep(8)
        signup .window_handle()
        time.sleep(8)
        signup.setUsername('getlove@test')
        signup .setPassword('')
        signup.click_on_signup_button()

    def test_signup_with_twitter_valid_password_and_null_username(self):
        signup = SignUp(self)
        signup .open_trado()
        signup .click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup .click_on_connect_link()
        signup.click_on_signup_link()
        signup .click_on_twitter_link()
        time.sleep(8)
        signup .window_handle()
        signup.setUsername('')
        signup .setPassword('test@@@###123')
        signup .click_on_signup_button()



    def test_signup_with_facebook_valid_credentials(self):
        signup  = SignUp(self)
        signup .open_trado()
        signup .click_option1()
        signup .click_option2()
        signup .click_save_button()
        signup .click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup .window_handle_facebook("0559477424", "david16#")
        time.sleep(3)


    def test_signup_with_facebook_invalid_password_and_valid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("0559477424", "david2324")
        time.sleep(3)

    def test_signup_with_facebook_invalid_password_and_invalid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("05594dvsj424", "david2324")
        time.sleep(3)

    def test_signup_with_facebook_valid_password_and_invalid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("0559477424", "david16#")
        time.sleep(3)

    def test_signup_with_facebook_null_password_and_null_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("", "")
        time.sleep(3)

    def test_signup_with_facebook_null_password_and_valid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("0559477424", "")
        time.sleep(3)

    def test_signup_with_facebook_valid_password_and_null_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup.window_handle_facebook_with_error_message("", "david16#")
        time.sleep(3)



    def test_signup_with_google_valid_credentials(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('getlove@gmail.com')
        signup.setPassword('test@@@###123')
        signup.click_on_signup_button()

    def test_signup_with_google_invalid_password_and_valid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('getlove@gmail.com')
        signup.setPassword('testdsiu323')
        signup.click_on_signup_button()

    def test_signup_with_google_invalid_password_and_invalid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('gedhcsdsyh')
        signup.setPassword('testdsiu323')
        signup.click_on_signup_button()

    def test_signup_with_google_valid_password_and_invalid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('gedhcsdsyh')
        signup.setPassword('test@@@###123')
        signup.click_on_signup_button()


    def test_signup_with_google_null_password_and_null_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('')
        signup.setPassword('')
        signup.click_on_signup_button()


    def test_signup_with_google_null_password_and_valid_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('getlove@gmail.com')
        signup.setPassword('')
        signup.click_on_signup_button()

    def test_signup_with_google_valid_password_and_null_username(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('')
        signup.setPassword('test@@@###123')
        signup.click_on_signup_button()

    def test_signup_with_valid_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('0523155678')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)

    def test_signup_with_invalid_less_than_ten_digit_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('0523155')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_signup_with_invalid_more_than_ten_digit_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('052315567866788')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_signup_with_invalid_string_value_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('svdgdgdtgcnfdjdfkd')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_signup_with_invalid_special_character_value_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('@#!$%^&*()_+')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in  error


    def test_login_with_invalid_special_character_and_number_value_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('@#!$%^&*()_+53637288')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_login_with_invalid_string_and_number_value_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('sfdgfhfhfjjf122433435')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter
        assert "טלפון לא תקין" in error


    def test_login_with_null_phone_number(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_privacy_policy()
        time.sleep(2)
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_getter2
        assert "נא למלא שדה" in  error

    def test_signup_by_phone_without_selecting_privacy_poicy(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        signup.setting_phone_number('0521679888')
        time.sleep(2)
        signup.setting_buisness_number("123453677886")
        signup.click_on_signup_button()
        time.sleep(5)
        error = signup.error_message_privacy_policy
        assert "Please Approve Our Policy" == error

    def test_signup_by_twitter_without_selecting_privacy_policy(self):
        signup = SignUp(self)
        signup.open_trado()
        signup .click_option1()
        signup.click_option2()
        signup.click_save_button()
        time.sleep(2)
        signup.click_on_connect_link()
        time.sleep(2)
        signup.click_on_signup_link()
        time.sleep(2)
        signup .click_on_twitter_link()
        time.sleep(8)
        signup .window_handle()
        time.sleep(8)
        signup.setUsername('getlove@test')
        signup .setPassword('test@@@###123')
        signup.click_on_signup_button()

    def test_signup_by_google_without_selecting_privacy_policy(self):
        signup = SignUp(self)
        signup.open_trado()
        signup.click_option1()
        signup.click_option2()
        signup.click_save_button()
        signup.click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_google_link()
        time.sleep(6)
        signup.window_handle()
        time.sleep(5)
        signup.setUsername('getachewayehu77@gmail.com')
        signup.setPassword('test@@@###123')
        signup.click_on_signup_button()

    def test_signup_by_facebbook_without_selecting_privacy_policy(self):
        signup  = SignUp(self)
        signup .open_trado()
        signup .click_option1()
        signup .click_option2()
        signup .click_save_button()
        signup .click_on_connect_link()
        signup.click_on_signup_link()
        time.sleep(6)
        signup.click_on_facebook_link()
        time.sleep(6)
        signup .window_handle_facebook("0559477424", "david16#")
        time.sleep(3)
        signup.setting_buisness_number("213424253534646")
        signup.click_on_signup_button()
