import pytest
# from Web.Page import Login
from Web.Page.login_page import Login
import time
import allure

class Test_Login:

    @allure.description('Test_login_with_valid_credentials')
    @allure.severity(allure.severity_level.CRITICAL)
    @pytest.mark.sanity
    def test_login_with_twitter_valid_credentials(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@test')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()

    def test_login_with_twitter_invalid_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@test')
        lg.setPassword('testdsiu323')
        lg.click_on_login_button()

    def test_login_with_twitter_invalid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('gedhcsdsyh')
        lg.setPassword('testdsiu323')
        lg.click_on_login_button()

    def test_login_with_twitter_valid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('gedhcsdsyh')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()


    def test_login_with_twitter_null_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('')
        lg.setPassword('')
        lg.click_on_login_button()


    def test_login_with_twitter_null_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@test')
        lg.setPassword('')
        lg.click_on_login_button()

    def test_login_with_twitter_valid_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()



    def test_login_with_facebook_valid_credentials(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(2)
        lg.click_option1()
        # time.sleep(2)
        lg.click_option2()
        # time.sleep(2)
        lg.click_save_button()
        time.sleep(4)
        lg.click_on_connect_link()
        time.sleep(5)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook("0559477424", "david16#")
        time.sleep(3)


    def test_login_with_facebook_invalid_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("0559477424", "david2324")
        time.sleep(3)

    def test_login_with_facebook_invalid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("05594dvsj424", "david2324")
        time.sleep(3)

    def test_login_with_facebook_valid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("0559477424", "david16#")
        time.sleep(3)

    def test_login_with_facebook_null_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("", "")
        time.sleep(3)

    def test_login_with_facebook_null_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("0559477424", "")
        time.sleep(3)

    def test_login_with_facebook_valid_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(6)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook_with_error_message("", "david16#")
        time.sleep(3)



    def test_login_with_google_valid_credentials(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@gmail.com')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()

    def test_login_with_google_invalid_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@gmail.com')
        lg.setPassword('testdsiu323')
        lg.click_on_login_button()

    def test_login_with_google_invalid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('gedhcsdsyh')
        lg.setPassword('testdsiu323')
        lg.click_on_login_button()

    def test_login_with_google_valid_password_and_invalid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('gedhcsdsyh')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()


    def test_login_with_google_null_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('')
        lg.setPassword('')
        lg.click_on_login_button()


    def test_login_with_google_null_password_and_valid_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@gmail.com')
        lg.setPassword('')
        lg.click_on_login_button()

    def test_login_with_google_valid_password_and_null_username(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('')
        lg.setPassword('test@@@###123')
        lg.click_on_login_button()


    def test_login_with_valid_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.setting_phone_number('0591111113')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(5)

    def test_login_with_invalid_less_than_ten_digit_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('05911')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_login_with_invalid_more_than_ten_digit_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('059113435344646')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_login_with_invalid_string_value_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('ytewewqtdfqwdghqw')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_login_with_invalid_special_character_value_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('@#!$%&*()^%%')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error


    def test_login_with_invalid_special_character_and_number_value_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('@#!$%232435')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error

    def test_login_with_invalid_string_and_number_value_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('qwers232435')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter
        assert "טלפון לא תקין" in  error




    def test_login_with_null_phone_number(self):
        lg = Login(self)
        lg.open_demoblaz()
        lg.click_option1()
        lg.click_option2()
        lg.click_save_button()
        lg.click_on_connect_link()
        time.sleep(3)
        lg.setting_phone_number('')
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(2)
        error = lg.error_message_getter2
        assert "נא למלא שדה" in  error


    def test_login_with_twitter_by_selecting_checkbox(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_twitter_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@test')
        lg.setPassword('test@@@###123')
        lg.click_checkbox()
        lg.click_on_login_button()

    def test_login_with_facebook_by_selecting_checkbox(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(2)
        lg.click_option1()
        # time.sleep(2)
        lg.click_option2()
        # time.sleep(2)
        lg.click_save_button()
        time.sleep(4)
        lg.click_on_connect_link()
        time.sleep(5)
        lg.click_on_facebook_link()
        time.sleep(6)
        lg.window_handle_facebook("0559477424", "david16#")
        time.sleep(3)
        lg.click_checkbox()

    def test_login_with_google_by_selecting_checkbox(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.click_on_google_link()
        time.sleep(8)
        lg.window_handle()
        time.sleep(8)
        lg.setUsername('getlove@gmail.com')
        lg.setPassword('test@@@###123')
        lg.click_checkbox()
        lg.click_on_login_button()

    def test_login_with_phone_by_selecting_checkbox(self):
        lg = Login(self)
        lg.open_demoblaz()
        time.sleep(7)
        lg.click_option1()
        time.sleep(2)
        lg.click_option2()
        time.sleep(2)
        lg.click_save_button()
        time.sleep(8)
        lg.click_on_connect_link()
        time.sleep(8)
        lg.setting_phone_number('0591111113')
        time.sleep(2)
        lg.click_checkbox()
        time.sleep(2)
        lg.click_on_login_button()
        time.sleep(5)

